(define (problem service-problem)
(:domain composition)
(:objects q0 - qstate q1 - qstate q2 - qstate q3 - qstate q4 - qstate q5 - qstate q6 - qstate q7 - qstate q8 - qstate q9 - qstate)
(:init (current_state_0 s0_handler_cleaning_0) (current_state_1 s1_handler_film_deposition_0) (current_state_2 s2_handler_resist_coating_0) (current_state_3 s3_handler_exposure_0) (current_state_4 s4_handler_development_0) (startsymb) (trans_mode) (oldautstate q1) (oldcnt_idx0 q1))
(:goal (and (dummy_goal) (current_state_0 s0_handler_cleaning_0)  (current_state_1 s1_handler_film_deposition_0)  (current_state_2 s2_handler_resist_coating_0)  (current_state_3 s3_handler_exposure_0)  (current_state_4 s4_handler_development_0) ))
)
